id: P004411
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:19:12.854528
source_metadata:
  id: bdr:W1KG21754
  title: བོད་ཀྱི་སྨན་རྩིས་ཆེད་རྩོམ་ཕྱོགས་བསྡུས།
  author: ''
  volumes:
    ca2d29656dbf4aacaf4cb3e9d3651883:
      image_group_id: I1KG21849
      title: ''
      volume_number: 1
      total_pages: 442
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
